### ISSUE TITLE
Is there a simple way to add supervisor names to gitbook output?

### ISSUE THREAD

**Issue by matanmazor** [ismayc/thesisdown#132]
Thanks :)

**Comment by ismayc** [comment]
Where would you like it to appear? Can you add an image?

**Comment by matanmazor** [comment]
Maybe something like this? 
![image](https://user-images.githubusercontent.com/20517901/109418279-81e64b80-79bf-11eb-88a9-39d144a26ca0.png)

**Comment by ismayc** [comment]
It's a little hacky but I think it should work for just adding this to the YAML of `index.Rmd`:

```yaml
title: 'My Awesome Thesis'
author: '**Dexter**'
date: '`r ifelse(knitr::is_html_output(), "Supervisors: Dee Dee & Mojo Jojo<br>April 2021", "April 2021")`'
```

<img width="427" alt="Screen Shot 2021-03-01 at 12 52 43 PM" src="https://user-images.githubusercontent.com/9215614/109557492-0a7eed80-7a8d-11eb-9d77-5fd2b5f3ae54.png">
